# Generated by Django 5.0.2 on 2024-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_alter_book_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publlishing',
            field=models.DateField(),
        ),
    ]
