# Generated by Django 5.0.2 on 2024-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_alter_book_year_of_publlishing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_of_publlishing',
            new_name='year_of_publishing',
        ),
    ]
