# Generated by Django 5.0.2 on 2024-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0004_rename_year_of_publlishing_book_year_of_publishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
